"""
Forward Outcome Tracker.

Closes the learning loop. Every signal generated by the system is followed
forward and its 5d/20d/60d outcomes are recorded against the original plan.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import UTC, date, datetime
from enum import Enum
from pathlib import Path
from typing import Any


DEFAULT_OUTCOMES_DIR = Path("reports/outcomes")
DEFAULT_OUTCOMES_JOURNAL = DEFAULT_OUTCOMES_DIR / "forward_outcomes.jsonl"
STANDARD_HORIZONS_DAYS = (5, 20, 60)


class OutcomeExitReason(str, Enum):
    STOP_HIT = "stop_hit"
    TARGET_1_HIT = "target_1_hit"
    TARGET_2_HIT = "target_2_hit"
    TIME_EXIT = "time_exit"
    NO_FILL = "no_fill"
    INSUFFICIENT_DATA = "insufficient_data"


@dataclass(frozen=True)
class SignalReference:
    signal_id: str
    symbol: str
    signal_date: date
    entry_trigger: float
    stop_loss: float
    target_1: float | None = None
    target_2: float | None = None
    setup_type: str = "unknown"
    market_regime: str = "unknown"
    risk_tier: str = "unknown"


@dataclass(frozen=True)
class HorizonOutcome:
    horizon_days: int
    bars_observed: int
    close_at_horizon: float | None
    r_multiple_at_horizon: float | None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class ForwardOutcome:
    signal_id: str
    symbol: str
    signal_date: str
    setup_type: str
    market_regime: str
    risk_tier: str
    entry_trigger: float
    stop_loss: float
    target_1: float | None
    target_2: float | None
    realized_entry: float | None
    entry_fill_day: int | None
    initial_risk: float
    mfe_r: float | None
    mae_r: float | None
    exit_reason: str
    exit_day: int | None
    exit_price: float | None
    realized_r: float | None
    horizons: list[HorizonOutcome] = field(default_factory=list)
    bars_used: int = 0
    warnings: list[str] = field(default_factory=list)
    computed_at: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "signal_date": self.signal_date,
            "setup_type": self.setup_type,
            "market_regime": self.market_regime,
            "risk_tier": self.risk_tier,
            "entry_trigger": self.entry_trigger,
            "stop_loss": self.stop_loss,
            "target_1": self.target_1,
            "target_2": self.target_2,
            "realized_entry": self.realized_entry,
            "entry_fill_day": self.entry_fill_day,
            "initial_risk": self.initial_risk,
            "mfe_r": self.mfe_r,
            "mae_r": self.mae_r,
            "exit_reason": self.exit_reason,
            "exit_day": self.exit_day,
            "exit_price": self.exit_price,
            "realized_r": self.realized_r,
            "horizons": [h.to_dict() for h in self.horizons],
            "bars_used": self.bars_used,
            "warnings": self.warnings,
            "computed_at": self.computed_at,
        }


def compute_forward_outcome(
    signal: SignalReference,
    forward_bars: list[dict[str, Any]],
    *,
    horizons_days: tuple[int, ...] = STANDARD_HORIZONS_DAYS,
    time_exit_days: int = 20,
) -> ForwardOutcome:
    warnings: list[str] = []
    direction = 1
    initial_risk = abs(signal.entry_trigger - signal.stop_loss)

    if initial_risk <= 0:
        return _empty_outcome(signal, initial_risk=0.0, warnings=["invalid_initial_risk"], exit_reason=OutcomeExitReason.INSUFFICIENT_DATA)

    if not forward_bars:
        return _empty_outcome(signal, initial_risk=initial_risk, warnings=["no_forward_bars"], exit_reason=OutcomeExitReason.INSUFFICIENT_DATA)

    realized_entry: float | None = None
    entry_fill_day: int | None = None
    mfe_price: float | None = None
    mae_price: float | None = None
    exit_reason = OutcomeExitReason.TIME_EXIT
    exit_day: int | None = None
    exit_price: float | None = None

    for day_index, bar in enumerate(forward_bars, start=1):
        try:
            open_p = float(bar["o"])
            high_p = float(bar["h"])
            low_p = float(bar["l"])
            close_p = float(bar["c"])
        except (KeyError, TypeError, ValueError):
            warnings.append(f"bar_{day_index}_invalid_shape")
            continue

        if realized_entry is None:
            if open_p >= signal.entry_trigger:
                realized_entry = open_p
                entry_fill_day = day_index
            elif high_p >= signal.entry_trigger:
                realized_entry = signal.entry_trigger
                entry_fill_day = day_index
            if realized_entry is None:
                continue

        if mfe_price is None or high_p > mfe_price:
            mfe_price = high_p
        if mae_price is None or low_p < mae_price:
            mae_price = low_p

        if low_p <= signal.stop_loss:
            exit_reason = OutcomeExitReason.STOP_HIT
            exit_day = day_index
            exit_price = signal.stop_loss
            break

        if signal.target_2 is not None and high_p >= signal.target_2:
            exit_reason = OutcomeExitReason.TARGET_2_HIT
            exit_day = day_index
            exit_price = signal.target_2
            break

        if signal.target_1 is not None and high_p >= signal.target_1:
            exit_reason = OutcomeExitReason.TARGET_1_HIT
            exit_day = day_index
            exit_price = signal.target_1
            break

        if day_index >= time_exit_days:
            exit_reason = OutcomeExitReason.TIME_EXIT
            exit_day = day_index
            exit_price = close_p
            break

    if realized_entry is None:
        return _empty_outcome(signal, initial_risk=initial_risk, warnings=["no_entry_fill_within_window"], exit_reason=OutcomeExitReason.NO_FILL)

    if exit_day is None and forward_bars:
        last_bar = forward_bars[-1]
        try:
            exit_price = float(last_bar["c"])
            exit_day = len(forward_bars)
            exit_reason = OutcomeExitReason.TIME_EXIT
        except (KeyError, TypeError, ValueError):
            warnings.append("final_bar_invalid")

    mfe_r = (mfe_price - realized_entry) * direction / initial_risk if mfe_price is not None else None
    mae_r = (mae_price - realized_entry) * direction / initial_risk if mae_price is not None else None
    realized_r = (exit_price - realized_entry) * direction / initial_risk if exit_price is not None else None

    horizons = _compute_horizon_outcomes(
        forward_bars=forward_bars,
        realized_entry=realized_entry,
        initial_risk=initial_risk,
        direction=direction,
        horizons_days=horizons_days,
    )

    return ForwardOutcome(
        signal_id=signal.signal_id,
        symbol=signal.symbol,
        signal_date=signal.signal_date.isoformat(),
        setup_type=signal.setup_type,
        market_regime=signal.market_regime,
        risk_tier=signal.risk_tier,
        entry_trigger=signal.entry_trigger,
        stop_loss=signal.stop_loss,
        target_1=signal.target_1,
        target_2=signal.target_2,
        realized_entry=round(realized_entry, 6),
        entry_fill_day=entry_fill_day,
        initial_risk=round(initial_risk, 6),
        mfe_r=round(mfe_r, 4) if mfe_r is not None else None,
        mae_r=round(mae_r, 4) if mae_r is not None else None,
        exit_reason=exit_reason.value,
        exit_day=exit_day,
        exit_price=round(exit_price, 6) if exit_price is not None else None,
        realized_r=round(realized_r, 4) if realized_r is not None else None,
        horizons=horizons,
        bars_used=len(forward_bars),
        warnings=warnings,
        computed_at=datetime.now(UTC).isoformat().replace("+00:00", "Z"),
    )


def _compute_horizon_outcomes(
    *,
    forward_bars: list[dict[str, Any]],
    realized_entry: float,
    initial_risk: float,
    direction: int,
    horizons_days: tuple[int, ...],
) -> list[HorizonOutcome]:
    outcomes: list[HorizonOutcome] = []
    for horizon in horizons_days:
        if horizon <= 0 or horizon > len(forward_bars):
            outcomes.append(HorizonOutcome(horizon_days=horizon, bars_observed=min(horizon, len(forward_bars)), close_at_horizon=None, r_multiple_at_horizon=None))
            continue
        try:
            close_at_horizon = float(forward_bars[horizon - 1]["c"])
        except (KeyError, TypeError, ValueError):
            outcomes.append(HorizonOutcome(horizon_days=horizon, bars_observed=horizon, close_at_horizon=None, r_multiple_at_horizon=None))
            continue
        r = (close_at_horizon - realized_entry) * direction / initial_risk
        outcomes.append(HorizonOutcome(horizon_days=horizon, bars_observed=horizon, close_at_horizon=round(close_at_horizon, 6), r_multiple_at_horizon=round(r, 4)))
    return outcomes


def append_outcome(outcome: ForwardOutcome, *, journal_path: Path = DEFAULT_OUTCOMES_JOURNAL) -> None:
    journal_path = Path(journal_path)
    journal_path.parent.mkdir(parents=True, exist_ok=True)
    with journal_path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(outcome.to_dict()) + "\n")


def load_outcomes(journal_path: Path = DEFAULT_OUTCOMES_JOURNAL) -> list[dict[str, Any]]:
    journal_path = Path(journal_path)
    if not journal_path.exists():
        return []
    outcomes: list[dict[str, Any]] = []
    with journal_path.open("r", encoding="utf-8") as handle:
        for line in handle:
            stripped = line.strip()
            if not stripped:
                continue
            try:
                outcomes.append(json.loads(stripped))
            except json.JSONDecodeError:
                continue
    return outcomes


def _empty_outcome(
    signal: SignalReference,
    *,
    initial_risk: float,
    warnings: list[str],
    exit_reason: OutcomeExitReason,
) -> ForwardOutcome:
    return ForwardOutcome(
        signal_id=signal.signal_id,
        symbol=signal.symbol,
        signal_date=signal.signal_date.isoformat(),
        setup_type=signal.setup_type,
        market_regime=signal.market_regime,
        risk_tier=signal.risk_tier,
        entry_trigger=signal.entry_trigger,
        stop_loss=signal.stop_loss,
        target_1=signal.target_1,
        target_2=signal.target_2,
        realized_entry=None,
        entry_fill_day=None,
        initial_risk=round(initial_risk, 6),
        mfe_r=None,
        mae_r=None,
        exit_reason=exit_reason.value,
        exit_day=None,
        exit_price=None,
        realized_r=None,
        horizons=[],
        bars_used=0,
        warnings=warnings,
        computed_at=datetime.now(UTC).isoformat().replace("+00:00", "Z"),
    )
