#!/usr/bin/env python3
"""Run historical setup validation against Polygon daily aggregate bars.

This script expects a JSON file containing backtest signals. The signal format
is intentionally close to `BacktestSignal` so it can be generated by future
report/signal pipelines without coupling to live trading.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from src.backtesting_framework import BacktestSignal
from src.historical_validation import (
    HistoricalValidationConfig,
    run_and_save_historical_validation,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run historical validation.")
    parser.add_argument("--signals-file", required=True, help="JSON file containing BacktestSignal-like objects.")
    parser.add_argument("--symbols", required=True, help="Comma-separated symbols to fetch from Polygon.")
    parser.add_argument("--start-date", required=True, help="Start date in YYYY-MM-DD format.")
    parser.add_argument("--end-date", required=True, help="End date in YYYY-MM-DD format.")
    parser.add_argument(
        "--horizons",
        default="5,10,20",
        help="Comma-separated holding horizons in trading days. Default: 5,10,20.",
    )
    parser.add_argument(
        "--output",
        default="reports/backtests/backtest_summary.json",
        help="Output JSON summary path.",
    )
    return parser.parse_args()


def _load_signals(path: Path) -> list[BacktestSignal]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise ValueError("signals file must contain a JSON list")

    signals: list[BacktestSignal] = []
    for item in payload:
        if not isinstance(item, dict):
            raise ValueError("each signal must be a JSON object")
        signals.append(
            BacktestSignal(
                timestamp_utc=str(item["timestamp_utc"]),
                symbol=str(item["symbol"]),
                market_state=str(item.get("market_state", "unknown")),
                setup_type=str(item.get("setup_type", "unknown")),
                decision=str(item.get("decision", "approved")),
                risk_tier=str(item.get("risk_tier", "unknown")),
                entry_price=float(item["entry_price"]),
                position_size_multiplier=float(item.get("position_size_multiplier", 1.0)),
                holding_days=int(item.get("holding_days", 5)),
            )
        )

    return signals


def main() -> int:
    args = parse_args()
    signals = _load_signals(Path(args.signals_file))
    symbols = tuple(symbol.strip() for symbol in args.symbols.split(",") if symbol.strip())
    horizons = tuple(int(item.strip()) for item in args.horizons.split(",") if item.strip())

    if not symbols:
        raise ValueError("at least one symbol is required")
    if not horizons:
        raise ValueError("at least one horizon is required")

    config = HistoricalValidationConfig(
        symbols=symbols,
        start_date=args.start_date,
        end_date=args.end_date,
        horizons=horizons,
        output_path=Path(args.output),
    )
    summary = run_and_save_historical_validation(signals, config)

    print(f"Historical validation written to: {config.output_path}")
    for metric in summary.metrics_by_horizon:
        print(
            f"{metric.horizon_days}d | samples={metric.sample_size} | "
            f"win_rate={metric.win_rate:.2%} | avg_return={metric.average_return:.2f}% | "
            f"MAE={metric.max_adverse_excursion:.2f}% | false_positive={metric.false_positive_rate:.2%}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
